filtering users by name and account type while exporting
llaske/sugarizer-server pull request #318
Opened 2022-03-27 19:45 UTC by saga2405

Now the users are getting filtered according to account type and name when we export users, rather than exporting all the accounts , only the filtered accounts are getting downloaded

2022-03-27 19:57 UTC, saga2405 commented
issue #313

2022-03-27 19:59 UTC, saga2405 commented
@llaske @NikhilM98 can you please review this request (#313 )

2022-04-03 02:03 UTC, NikhilM98 commented
There are several changes which are not relevant to the issue (comments, unwanted spaces). Can you please remove them?

Also, if you look at the git diff, you'll find some "end of line" errors, can you please get rid of them too?

2022-04-03 12:53 UTC, saga2405 commented
sure, I'll do that

2022-04-04 07:29 UTC, saga2405 commented
@NikhilM98 done

2022-07-23 08:24 UTC, llaske requested changes
Good job. It works and it's useful.
BTW it's no longer possible to export every users which is require.
I suggest to add an option to do that in the combo to allow Students/Teacher/Admin + All.

See also my comments below and remove comments on every line of your change.

2022-07-23 08:24 UTC, llaske commented on add-admin.sh
> +curl -k -i -H "Content-Type: application/x-www-form-urlencoded" -X POST -d "${newobject}" $3
Remove this change from the PR

2022-07-23 08:24 UTC, llaske commented on docs/install.md
> +	curl -L "https://github.com/docker/compose/releases/download/1.8.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
Remove this change from the PR

2022-07-23 08:24 UTC, llaske commented on env/sugarizer.ini
> +version = 1.4.0
Remove this change from the PR

2022-07-23 08:24 UTC, llaske commented on package-lock.json
> +	"lockfileVersion": 1,
Remove changes in this file from the PR

2023-02-04 10:02 UTC, llaske commented
Closed due to lack of activity.

2023-02-04 10:02 UTC, closed without merging