Users next page button fix
llaske/sugarizer-server pull request #379
Opened 2023-03-04 08:16 UTC by Asymmentric

##### Fix for the issue https://github.com/llaske/sugarizer-server/issues/364

Complete: 
- Fixed 'Next page >>' and '<< Previous page' buttons on `dashboard/users`  which now considers the search criteria while displaying user details
- form on `/dashboard/users` has 'username' as query parameter, so replaced 'q' query parameters by 'username' throughout 

In Progress:
- 'Next page >>' for assignments

2023-03-04 08:20 UTC, NikhilM98 commented
Can you clean this PR?
- Get rid of commits which are not yours.
- Remove unnecessary comments and white space from the code.

2023-03-04 08:51 UTC, Asymmentric commented
hi @NikhilM98 
i tried cleaning it. Please let me know if it can be improved

2023-03-04 08:59 UTC, NikhilM98 requested changes

2023-03-04 08:59 UTC, NikhilM98 commented on docs/migrate.md
> +The id is the one on the line named `sugarizer-server_mongodb`.
Create a different PR to address this typo.

2023-03-04 08:59 UTC, NikhilM98 commented on api/controller/users.js
> +		if(filter=='username'){
There is no point in replacing `q` with `username`. `q` is commonly used for search operations.

2023-03-04 08:59 UTC, NikhilM98 commented on api/controller/users.js
> -
These delete line changes are unnecessary.

2023-03-04 08:59 UTC, NikhilM98 commented on api/controller/users.js
>   * @apiSuccess {Object} color Buddy color
What's the purpose of this change?

2023-03-04 08:59 UTC, NikhilM98 commented on dashboard/controller/users/index.js
> +
The changes with extra whitespaces are unnecessary.

2023-03-04 09:01 UTC, NikhilM98 commented
In this PR I can see that you have changed some variable names, but how does it fixes the next page button issue?

2023-03-04 10:41 UTC, Asymmentric commented
Suppose when the SHOW RESULTS button is clicked it requests   `_dashboard/users?username=n&role=student_` here it was fetching the results good and it was being resolved as  `query['q']=req.query.username`  but the _next_page_ links which were being created by `formPaginatedUrl()` looked something like  `_dashboard/users?q=n&role=student&offset=10&limit=10_` 

The problem was due to `req.query.q` not being handled there so the search criteria was not being considered.

2023-03-04 13:13 UTC, NikhilM98 commented
I just tested the issue. I see what you mean. However, it may be better if the keys like `username`, `name`, and `classroom` are reserved for exact string matching. For searching with partial string matching, it may be better to use `q`.

What do you think about doing something like [this](https://github.com/NikhilM98/sugarizer-server/commit/642260896f1e882c7fbcd685c6b36851dbfee0c2)?

2023-03-04 14:55 UTC, Asymmentric commented
True, that is a fair approach but rather than changing element names in the ejs file can this be a possible solution 

By handling _req.query.q_

`if (req.query.username != '' || req.query.q!='') {
 query['q'] = req.query.username || req.query.q;
 }`

`if (req.query.classroom != '' || req.query.q!='') {
 query['q'] = req.query.classroom || req.query.q;
 }`

2023-03-04 15:22 UTC, NikhilM98 commented
Yes this is a possible solution too, but it is prone to unexpected behavior, for example if in future both variables are defined. Also, it may be confusing to use two variables for the same parameter.

2023-03-05 03:15 UTC, Asymmentric commented
Yes sure it might make it inconsistent

2023-03-05 08:04 UTC, NikhilM98 commented
Can you make your changes consistent with the suggested ones and squash your commits

2023-03-06 17:27 UTC, Asymmentric commented
@NikhilM98 I've made the changes. Let know if any improvements

2023-03-06 18:21 UTC, NikhilM98 commented
There are several changes in this PR which are not relevant to this issue: [changes](https://github.com/llaske/sugarizer-server/pull/379/files).

Can you remove the unnecessary changes and squash your commits into one or two commits?

2023-03-07 01:19 UTC, kartikaysaxena commented
Can I contribute to the same?

2023-03-07 02:02 UTC, NikhilM98 commented
@kartikaysaxena the solution is already finalized and coded. This tasks doesn't require collaboration between multiple contributions for now. Feel free to experiment with Sugarizer Server and report any issues you find in the application.

2023-09-05 20:01 UTC, llaske commented
@Asymmentric could you close one of the two PR?

2023-09-06 04:13 UTC, closed without merging