Users next page button fix
llaske/sugarizer-server pull request #406
Opened 2023-09-03 15:40 UTC by Asymmentric

2023-09-03 17:18 UTC, Asymmentric commented
@NikhilM98 . can you please go through it once.

2023-09-05 20:01 UTC, llaske commented
@Asymmentric could you close one of the two PR?

2023-09-06 04:14 UTC, Asymmentric commented
Sure @llaske . I have closed the previous PR.

2023-09-06 20:05 UTC, llaske requested changes
It doesn't work, there is a fatal error.

![image](https://github.com/llaske/sugarizer-server/assets/981841/1cad4ab3-6562-41f2-a68e-f1f38b148dba)

Plus I've got doubt regarding your fix.

2023-09-06 20:05 UTC, llaske commented on api/controller/users.js
> +	query=addQuery('q',req.query,query)
Avoid changing only indentation

2023-09-06 20:05 UTC, llaske commented on api/controller/users.js
> -
Avoid changing only indentation

2023-09-06 20:05 UTC, llaske commented on api/controller/users.js
> -
Avoid changing only indentation

2023-09-06 20:05 UTC, llaske commented on api/controller/users.js
> -
Avoid changing only indentation

2023-09-06 20:05 UTC, llaske commented on api/controller/users.js
> +		collection.aggregate(conf, async function(err, users) {
This not suppose to be async

2023-09-06 20:05 UTC, llaske commented on api/controller/users.js
> +		if(filter=='q'){
I don't understand this double comparison

2023-09-07 08:27 UTC, Asymmentric commented
hey @llaske  There was some issue with my git in the previous commits. Now its fixed.

2023-09-07 20:06 UTC, llaske requested changes
It works now.
Please fix the indentation since for maintenance reason we should be able to quickly identify lines changed.
Also the PR should be done on dev branch.

2023-09-07 20:06 UTC, llaske commented on api/controller/users.js
> + * @apiSuccessearchs {String} role User role (student or admin)
It's a typo, there is no reason to change the comment here

2023-09-07 20:06 UTC, llaske commented on api/controller/users.js
> +	query=addQuery('q',req.query,query)
Should be fixed

2023-09-07 20:06 UTC, llaske commented on api/controller/users.js
> -
Should be fixed

2023-09-07 20:06 UTC, llaske commented on api/controller/users.js
> -
Should be fixed

2023-09-07 20:06 UTC, llaske commented on api/controller/users.js
> +		collection.aggregate(conf, async function(err, users) {
Should be fixed

2023-09-07 20:06 UTC, llaske commented on api/controller/users.js
> -
Should be fixed

2023-09-07 20:06 UTC, llaske commented on api/controller/users.js
> +
Should be fixed

2023-09-07 20:06 UTC, llaske commented on dashboard/controller/users/index.js
> +
Should be fixed

2023-09-07 20:06 UTC, llaske commented on dashboard/controller/users/searchUser.js
> +		query['q']=req.query.q;
Should be fixed

2023-09-07 20:06 UTC, llaske commented on dashboard/controller/users/searchUser.js
> +
Should be fixed

2023-09-08 06:38 UTC, closed without merging